create_page_type: true
node_settings:
    defaults:
        options:
            - status
        comments: COMMENT_NODE_HIDDEN
        submitted: false
        menus:
            - main-menu
        node_preview_[type]: false
        pathauto_node_[type]_pattern: '[node:menu-link:parents:join-path]/[node:title]'
