'anonymous user':
    - 'access content'
    - 'view any bean_rte_rte bean'
    - 'view files'
'authenticated user':
    - 'access content'
    - 'view any bean_rte_rte bean'
    - 'view files'
admin:
    - 'access all views'
    - 'access content'
    - 'access content overview'
    - 'access overlay'
    - 'access statistics'
    - 'access the dashboard page'
    - 'access user profiles'
    - 'administer blocks'
    - 'administer files'
    - 'administer menu'
    - 'administer nodes'
    - 'administer site configuration'
    - 'administer taxonomy'
    - 'administer permissions'
    - 'administer tiles'
    - 'administer users'
    - 'administer xmlsitemap'
    - 'bypass file access'
    - 'bypass node access'
    - 'configure ombuseo'
    - 'configure ombu site'
    - 'create page content'
    - 'create url aliases'
    - 'delete any page content'
    - 'delete own page content'
    - 'delete revisions'
    - 'edit any page content'
    - 'edit own page content'
    - 'edit supplementary content'
    - 'redirect from admin to dashboard'
    - 'revert revisions'
    - 'show dashboard toolbar'
    - 'use text format default'
    - 'use tinymce html button'
    - 'view own unpublished content'
    - 'view post access counter'
    - 'view revisions'
    - 'view the administration theme'
editor:
    - 'access content overview'
    - 'access contextual links'
    - 'access overlay'
    - 'access the dashboard page'
    - 'add tiles'
    - 'add media from remote sources'
    - 'administer blocks'
    - 'administer menu'
    - 'administer nodes'
    - 'administer redirects'
    - 'administer taxonomy'
    - 'administer tiles'
    - 'arrange tiles'
    - 'bypass file access'
    - 'create any bean_rte_rte bean'
    - 'create page content'
    - 'create url aliases'
    - 'delete any bean_rte_rte bean'
    - 'delete any page content'
    - 'delete own page content'
    - 'delete revisions'
    - 'edit any bean_rte_rte bean'
    - 'edit any page content'
    - 'edit ombuseo fields'
    - 'edit own page content'
    - 'edit supplementary content'
    - 'import media'
    - 'redirect from admin to dashboard'
    - 'revert revisions'
    - 'show dashboard toolbar'
    - 'use text format default'
    - 'view bean page'
    - 'view revisions'
    - 'view the administration theme'
