menu_secondary_links_source: header-links

# Local settings.
site_default_country: US
date_first_day: 1

# Default 404 page.
site_404: ombucore_404

# Date & time settings.
date_default_timezone: America/Los_Angeles
configurable_timezones: 0

# Error reporting:
#  0 - Write errors to the log.
#  1 - Write errors to the log and to the screen.
error_level: 0

# Enable access logs.
statistics_enable_access_log: true

# Set default contact status (gets added to the users data field)
contact_default_status: 0;

# Registration settings:
#  0 - Only site admins can create new accounts.
#  1 - Visitors can create accounts without admin approval.
#  2 - Visitors can create accounts with admin approval.
user_register: 0;

# Require email varification when a visitor creates an account
user_email_verification: 0;

# Enable SEO on page content types.
ombuseo_node_page: 1

# oEmbed / media settings
default_oembedcore_provider:
    youtube: false
    vimeo: false
    flickr: false
    qik: false
    revision3: false
    twitter: false
media__wysiwyg_browser_plugins:
  - upload
  - media_default--media_browser_1
  - media_internet

# Update Action
#  0 - Do nothing. Leave the old alias intact.
#  1 - Create a new alias. Leave the existing alias functioning.
#  2 - Create a new alias. Delete the old alias.
pathauto_update_action: '2'

# Reduce strings to letters and numbers from ASCII-96.
pathauto_reduce_ascii: true
pathauto_node_applytofeeds: ''

# Default node pattern.
pathauto_node_pattern: '[node:title]'

# Node pattern for pages, use menu structure.
pathauto_node_page_pattern: '[node:menu-link:parents:join-path]/[node:title]'

# Disable auto redirects.
redirect_auto_redirect: 0

# Update jQuery to 1.7. Needed in order for Bootstrap JS components to work.
jquery_update_compression_type: 'min'
jquery_update_jquery_cdn: 'none'
jquery_update_jquery_version: '1.10'

# Apply select2 to all select fields.
select2_use_for_ac_elements: 1
select2_use_for_all_select_elements: 1
select2_use_for_all_select_elements_for_admin_pages: 1
select2_excluded_ids: 'core-content-select'

# Special menu items
special_menu_items_separator: 0
special_menu_items_nolink_tag: '<a>'

# Show title in breadcrumbs
breadcrumb_show_page_title: 1

# Set default permissions for new directories and files.
# Note that these are decimal representations of octal numbers:
#  1528 = 02770
#  432  = 0660
file_chmod_directory: 1528
file_chmod_file: 432
