default:
    format: default
    editor: ckeditor
    settings:
        default: 1
        user_choose: 0
        show_toggle: 1
        theme: advanced
        language: en
        buttons:
            default:
                Bold: 1
                Italic: 1
                JustifyLeft: 1
                JustifyCenter: 1
                JustifyRight: 1
                BulletedList: 1
                NumberedList: 1
                Link: 1
                Unlink: 1
                Blockquote: 1
                HorizontalRule: 1
                Format: 1
                Styles: 1
            ombucleanup:
                ombucleanup: 1
            drupal:
                media: 1
        toolbar_loc: top
        toolbar_align: left
        path_loc: bottom
        resizing: 1
        default_toolbar_grouping: 0
        verify_html: 1
        preformatted: 0
        convert_fonts_to_spans: 1
        remove_linebreaks: 1
        apply_source_formatting: 0
        paste_auto_cleanup_on_paste: 0
        block_formats: 'p,h2,h3,h4,h5,h6,pre'
        css_setting: self
        css_path: '%b%t/css/wysiwyg.css'
        css_classes: "Image Left=div.pull-left\r\nImage Right=div.pull-right\r\nButton=a.btn\r\nCall-to-action=a.cta\r\nPull Left=p.pull-left\r\nPull Right=p.pull-right\r\nLead Text=p.lead\r\nInline List=ul.inline"
    rdf_mapping: {  }
